# ==============================================================================
# database — RDS PostgreSQL with PostGIS, private, credential in SSM
# ==============================================================================
#
# THE CREDENTIAL RULE
#   The master password is generated by Terraform and written straight into SSM
#   Parameter Store as a SecureString. It is NEVER a Terraform output, never in
#   the repository, never a GitHub secret. The API reads it from SSM at cold
#   start; you read it from SSM when you need to connect.
#
#   It does still appear in the Terraform STATE file — unavoidable with a
#   generated password — which is exactly why the state bucket is private,
#   encrypted and versioned.
#
# POSTGIS IS NOT AUTOMATIC
#   RDS ships the extension but does not enable it. After the first apply,
#   connect through the bastion and run:
#
#       CREATE EXTENSION IF NOT EXISTS postgis;
#       SELECT postgis_version();
#
#   That belongs in the FIRST ALEMBIC MIGRATION, not a one-off psql session, so
#   a rebuilt database gets it automatically.
#
# COST
#   db.t4g.micro + 20 GB gp3 is roughly USD $17/month if left running. Stop it
#   when you are not working:
#       aws rds stop-db-instance --db-instance-identifier sportable-staging-db
#   A stopped instance bills storage only (~$2/month) and restarts itself after
#   7 days, at which point you stop it again.
# ==============================================================================

# ------------------------------------------------------------- subnet group
# The reason the network module builds an empty second private subnet.
resource "aws_db_subnet_group" "this" {
  name        = "${var.name_prefix}-db-subnet-group"
  description = "Private subnets across two AZs, as RDS requires"
  subnet_ids  = var.subnet_ids

  tags = { Name = "${var.name_prefix}-db-subnet-group" }
}

# ---------------------------------------------------------- parameter group
resource "aws_db_parameter_group" "this" {
  name        = "${var.name_prefix}-pg16"
  family      = "postgres16"
  description = "PostgreSQL 16 parameters for SportAble"

  # Reject unencrypted connections. libpq negotiates TLS by default, so psql,
  # psycopg and SQLAlchemy all keep working with no client change.
  parameter {
    name         = "rds.force_ssl"
    value        = "1"
    apply_method = "pending-reboot"
  }

  # Log any statement slower than a second. Cheap, and the first thing you want
  # when the venue search feels slow during a demo.
  parameter {
    name         = "log_min_duration_statement"
    value        = "1000"
    apply_method = "immediate"
  }

  tags = { Name = "${var.name_prefix}-pg16" }

  lifecycle {
    create_before_destroy = true
  }
}

# --------------------------------------------------------------- log group
# Created BEFORE the instance, deliberately. RDS will create this log group
# itself if it does not exist — with retention set to "never expire". Creating
# it first means the retention below is what applies.
resource "aws_cloudwatch_log_group" "postgresql" {
  # checkov:skip=CKV_AWS_338:Retaining slow-query logs for a year is a
  #   compliance rule for regulated production systems. This is a nine-week
  #   student staging database, and 12 months of retention would outlive the
  #   project while consuming the 5 GB CloudWatch free allowance.
  # checkov:skip=CKV_AWS_158:KMS encryption on log groups adds a customer
  #   managed key (~USD $1/month) to protect slow-query text in a staging
  #   database holding public open data. Logs are already encrypted at rest by
  #   CloudWatch's own key.
  name              = "/aws/rds/instance/${var.name_prefix}-db/postgresql"
  retention_in_days = var.log_retention_days

  tags = { Name = "${var.name_prefix}-db-logs" }
}

# ---------------------------------------------------------------- password
# override_special omits characters RDS rejects in a master password:
# forward slash, at sign, double quote and space.
resource "random_password" "master" {
  length           = 32
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

# ---------------------------------------------------------------- instance
resource "aws_db_instance" "this" {
  # checkov:skip=CKV_AWS_157:Multi-AZ doubles the bill for a staging database
  #   whose data is rebuildable from open-data sources by re-running ingestion.
  #   Revisit for production in Iteration 2.
  # checkov:skip=CKV_AWS_118:Enhanced monitoring requires an IAM role
  #   (rds-monitoring-role). The deploy principal on this account has no
  #   iam:CreateRole, so this is blocked rather than declined.
  # checkov:skip=CKV_AWS_353:Performance Insights is not enabled. Support on
  #   the smallest burstable classes is inconsistent, and an apply that fails on
  #   it costs more than the insight is worth at this stage.
  # checkov:skip=CKV_AWS_226:Minor version upgrades are pinned deliberately so
  #   the demo environment cannot change during assessment week. Re-enable after
  #   6 Sep 2026.
  # checkov:skip=CKV_AWS_293:Deletion protection is off so `terraform destroy`
  #   works on a staging environment that is meant to be disposable. It must be
  #   ON for production.
  identifier = "${var.name_prefix}-db"

  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  db_name  = var.database_name
  username = var.master_username
  password = random_password.master.result
  port     = 5432

  allocated_storage     = var.allocated_storage
  max_allocated_storage = 0 # no storage autoscaling: bounds the bill
  storage_type          = "gp3"
  storage_encrypted     = true

  # The whole point of T1. No public address exists, and the security group
  # accepts 5432 from the lambda and bastion groups only.
  publicly_accessible    = false
  db_subnet_group_name   = aws_db_subnet_group.this.name
  vpc_security_group_ids = [var.security_group_id]
  parameter_group_name   = aws_db_parameter_group.this.name

  multi_az                   = false
  auto_minor_version_upgrade = false

  # Free: backup storage up to the instance's allocated storage costs nothing.
  backup_retention_period = var.backup_retention_days
  backup_window           = "16:00-17:00" # 02:00–03:00 AEST, off-peak locally
  maintenance_window      = "sun:17:00-sun:18:00"
  copy_tags_to_snapshot   = true

  # Costs nothing to enable and satisfies the IAM-auth check. Actually using it
  # needs IAM policies we cannot create yet; the password path remains primary.
  iam_database_authentication_enabled = true

  enabled_cloudwatch_logs_exports = ["postgresql"]

  # Staging is disposable: no final snapshot, no deletion protection, changes
  # applied at once rather than waiting for the maintenance window.
  skip_final_snapshot = true
  deletion_protection = false
  apply_immediately   = true

  tags = { Name = "${var.name_prefix}-db" }

  depends_on = [aws_cloudwatch_log_group.postgresql]
}

# ---------------------------------------------------- credentials into SSM
# SecureString uses the AWS-managed key alias/aws/ssm, which is free. A customer
# managed key would cost ~USD $1/month and add nothing here.
resource "aws_ssm_parameter" "db_password" {
  # checkov:skip=CKV_AWS_337:SecureString with the AWS-managed key
  #   alias/aws/ssm, which is free. A customer managed key costs ~USD $1/month
  #   plus per-request charges; access is already governed by IAM, and no
  #   principal outside this account can read the parameter either way.
  name        = "${var.ssm_prefix}/db/password"
  description = "RDS master password. Generated by Terraform; never printed."
  type        = "SecureString"
  value       = random_password.master.result

  tags = { Name = "${var.name_prefix}-db-password" }
}

resource "aws_ssm_parameter" "db_url" {
  # checkov:skip=CKV_AWS_337:As above — AWS-managed KMS key, no CMK.
  name        = "${var.ssm_prefix}/db/url"
  description = "Full connection string. Read by the API at cold start and by Alembic in the pipeline."
  type        = "SecureString"
  value = format(
    "postgresql://%s:%s@%s:%d/%s",
    var.master_username,
    urlencode(random_password.master.result),
    aws_db_instance.this.address,
    aws_db_instance.this.port,
    var.database_name,
  )

  tags = { Name = "${var.name_prefix}-db-url" }
}

# Non-secret connection details, as plain String parameters. Handy for the Data
# team's tunnel command without handing anyone the password.
# These two are deliberately plain String, not SecureString. A hostname that
# resolves only inside the VPC and a database name are not secrets, and keeping
# them readable means the Data team can build a tunnel command without being
# granted decrypt on the password parameter.
resource "aws_ssm_parameter" "db_host" {
  # checkov:skip=CKV2_AWS_34:Not a secret — a private DNS name unreachable from
  #   outside the VPC. Encrypting it would force a decrypt grant on anyone who
  #   just needs the hostname.
  name  = "${var.ssm_prefix}/db/host"
  type  = "String"
  value = aws_db_instance.this.address
  tags  = { Name = "${var.name_prefix}-db-host" }
}

resource "aws_ssm_parameter" "db_name" {
  # checkov:skip=CKV2_AWS_34:Not a secret — the literal string "sportable",
  #   which is already in this repository.
  name  = "${var.ssm_prefix}/db/name"
  type  = "String"
  value = var.database_name
  tags  = { Name = "${var.name_prefix}-db-name" }
}
