"""Alembic environment for SportAble Melbourne.

Owned by the Infra/Platform engineer. This file resolves the database URL and
runs migrations; it does not define schema. Backend engineers add revisions to
``versions/`` and, when models exist, point ``target_metadata`` at them.

URL resolution, in order:

1. ``DATABASE_URL`` environment variable — local development and CI
   (testcontainers sets this).
2. ``SSM_DB_URL_PARAM`` environment variable naming an SSM Parameter Store
   SecureString — how the deploy pipeline supplies it in AWS.

A connection string is never committed and never written to Terraform state
output.
"""

from __future__ import annotations

import logging
import os

from alembic import context
from sqlalchemy import engine_from_config, pool

config = context.config
logger = logging.getLogger("alembic.env")

# Backend engineers: when SQLAlchemy models land, replace this with
#     from app.models import Base
#     target_metadata = Base.metadata
# so that `alembic revision --autogenerate` works.
target_metadata = None

# PostGIS installs these into the database. They are not ours and must never
# appear in an autogenerated revision.
EXCLUDED_TABLES = {"spatial_ref_sys", "geography_columns", "geometry_columns"}
EXCLUDED_SCHEMAS = {"tiger", "tiger_data", "topology"}


def _database_url() -> str:
    """Resolve the database URL, preferring the local/CI environment variable."""
    url = os.environ.get("DATABASE_URL")
    if url:
        return url

    param_name = os.environ.get("SSM_DB_URL_PARAM")
    if not param_name:
        raise RuntimeError(
            "No database URL available. Set DATABASE_URL for local or CI use, "
            "or SSM_DB_URL_PARAM to the name of an SSM SecureString parameter."
        )

    import boto3  # imported lazily so local runs need no AWS dependency

    client = boto3.client("ssm")
    logger.info("Resolving database URL from SSM parameter %s", param_name)
    response = client.get_parameter(Name=param_name, WithDecryption=True)
    return response["Parameter"]["Value"]


def include_object(obj, name, type_, reflected, compare_to) -> bool:  # noqa: ANN001
    """Keep PostGIS's own objects out of autogenerated revisions."""
    if type_ == "table":
        if name in EXCLUDED_TABLES:
            return False
        if getattr(obj, "schema", None) in EXCLUDED_SCHEMAS:
            return False
    return True


def run_migrations_offline() -> None:
    """Emit SQL to stdout without connecting. Used to review a migration."""
    context.configure(
        url=_database_url(),
        target_metadata=target_metadata,
        literal_binds=True,
        include_object=include_object,
        compare_type=True,
        dialect_opts={"paramstyle": "named"},
    )
    with context.begin_transaction():
        context.run_migrations()


def run_migrations_online() -> None:
    """Connect and apply migrations. This is what the deploy pipeline runs."""
    url = _database_url()
    config.set_main_option("sqlalchemy.url", url)

    # connect_timeout is a libpq option. Guard it so the same env.py also works
    # against SQLite, which CI and local smoke checks use before Postgres exists.
    connect_args = {"connect_timeout": 10} if url.startswith("postgresql") else {}

    connectable = engine_from_config(
        config.get_section(config.config_ini_section, {}),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,  # a migration job is short-lived; never pool
        connect_args=connect_args,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            include_object=include_object,
            compare_type=True,
            transaction_per_migration=True,
        )
        with context.begin_transaction():
            context.run_migrations()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
